#ifndef SLIMSHADY_WIDGETTYPE_H
#define SLIMSHADY_WIDGETTYPE_H

enum class WidgetType : int {
	TEXT_EDITOR = 0,
	SCENE_EDITOR = 1,
	CONSOLE = 2,
	FILE_BROWSER = 3,
	TASK = 4,
};

#endif //SLIMSHADY_WIDGETTYPE_H